project_name: join-pdf

builds:
  - id: cli
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: join-pdf

  - id: gui
    main: ./main.go
    goos: [windows]
    goarch: [amd64]
    ldflags:
      - -H=windowsgui -s -w -X main.version={{.Version}}
    binary: join-pdf-gui

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds: [cli]

  - id: windows-gui
    format: zip
    name_template: "{{ .ProjectName }}-gui_{{ .Version }}_windows_{{ .Arch }}"
    builds: [gui]
    files:
      - assets/icon.ico

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "dev"

changelog:
  skip: true
